#General Variable
prelim_exam: https://github.com/qrjhjimenez/sysad2-12021.git

username: qrjhjimenez

#ftp
writable_chroot: allow_writeable_chroot=YES

ftp_config: "allow_writeable_chroot=YES\npasv_min_port=30000\npasv_max_port=31000\nuserlist_file=/etc/vsftpd/user_list\nuserlist_deny=NO"

ftp_debian: "pasv_enable=Yes\npasv_min_port=10000\npasv_max_port=10100\nallow_writeable_chroot=YES\nssl_tlsv1=YES\nssl_sslv2=NO\nssl_sslv3=NO"

user: ftpuser

ftp_pass: $5$ftpassword$vbY6RyJrCfV3QpdnfvvMwhgbncvPgjgXrK80FjbuoJ9


#Nagios

naguser_pass: $5$strongpassword$ia6blGkj9UxynrEPd/oFMRM1nluLTdpbUpYrlzrwVPD

nagadmin_pass: strongestpass
