---
# tasks file for roles/grafana
- name: Installing Nginx
  apt:
   name: nginx
   update_cache: yes

- name: Importing the Grafana public GPG key into APT
  apt_key:
   url: https://packages.grafana.com/gpg.key
   state: present

- name: Adding Grafana source list
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present

- name: Updating packages
  apt:
   update_cache: yes

- name: Installing Grafana
  apt:
   name: grafana
   update_cache: yes


- name: Starting Grafana server
  service:
   name: grafana-server
   state: started
   enabled: yes

- name: Configuring Nginx
  copy:
   src: grafana_nginx
   dest: /etc/nginx/sites-available

- name: Reloading Nginx
  systemd:
   name: nginx
   state: reloaded

- name: Disabling Registration
  replace:
   path: /etc/grafana/grafana.ini
   regexp: ";allow_sign_up = true"
   replace: "allow_sign_up = false"
   after: "# disable user signup / registration"

- name: Disabling Anonymous Access
  replace:
   path: /etc/grafana/grafana.ini
   regexp: ";enabled = false"
   replace: "enabled = false"
   after: "# enable anonymous access"

- name: Restarting Grafana
  systemd:
   name: grafana-server
   state: restarted
