---
# tasks file for roles/elasticsearch
- name: Installing java
  apt:
   name: openjdk-11-jdk

- name: Importing the Elasticserach public GPG key into APT
  apt_key:
   url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
   state: present

- name: Adding Elastic source list
  lineinfile: 
   path: /etc/apt/sources.list.d/elastic-7.x.list
   line: '{{ elastic_source }}'
   create: yes

- name: Update packages
  apt:
   update_cache: yes

- name: Install Elasticsearch
  apt:
   name: elasticsearch
   update_cache: yes

- name: Configuring cluster name in elasticsearch.yml
  replace:
   path: /etc/elasticsearch/elasticsearch.yml
   regexp: '#cluster.name: my-application'
   replace: 'cluster.name: my-application'

- name: Configuring node in elasticsearch.yml
  replace:
   path: /etc/elasticsearch/elasticsearch.yml
   regexp: '#node.name: node-1'
   replace: 'node.name: node-1'

- name: Configuring network host in elasticsearch.yml
  replace:
   path: /etc/elasticsearch/elasticsearch.yml
   regexp: '#network.host: 192.168.0.1'
   replace: '{{ elastic_network }}'

- name: Configuring port in elasticsearch.yml
  replace:
   path: /etc/elasticsearch/elasticsearch.yml
   regexp: '#http.port: 9200'
   replace: 'http.port: 9200'

- name: Increasing service startup timeout
  lineinfile:
   path: /etc/systemd/system/elasticsearch.service.d/startup-timeout.conf
   line: '{{ elastic_timeout }}'
   create: yes
  register: timeout

- name: Restarting systemd manager
  systemd:
   daemon_reload: yes
  when: timeout.changed

- name: Start Elasticsearch Service
  service:
   name: elasticsearch
   enabled: yes
   state: started
