---
# tasks file for roles/kibana
- name: Stop and Remove elasticsearch container
  docker_container:
   name: elasticsearch
   state: absent

- name: Create network named elastic
  docker_network:
   name: elastic

- name: Download and create elasticsearch container
  docker_container:
   name: elasticsearch
   image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
   networks:
    - name: elastic
   networks_cli_compatible: yes
   env:
    discovery.type: "single-node"
   ports:
      - 9200:9200
      - 9300:9300

- name: Download and create kibana container
  docker_container:
   name: kibana
   image: docker.elastic.co/kibana/kibana:7.10.1
   networks: 
    - name: elastic
   networks_cli_compatible: yes
   env:
    discovery.type: "single-node"
   ports:
      - 5601:5601
