---
# tasks file for roles/InstallingCore
- name: Extracting Nagios Core
  unarchive:
   src: /downloads/nagios-4.2.1.tar.gz
   dest: /downloads
   remote_src: yes

- name: Configuring Nagios Script
  shell: ./configure --with-command-group=nagcmd --with-command-group=nagcmd --with-httpd_conf=/etc/apache2/sites-enabled/
  args:
   chdir: /downloads/nagios-4.2.1

- name: Compiling Nagios Core
  make:
   chdir: /downloads/nagios-4.2.1
   target: all
 
- name: Installing Binaries
  make:
   chdir: /downloads/nagios-4.2.1
   target: install

- name: Installing init script
  make:
   chdir: /downloads/nagios-4.2.1
   target: install-init

- name: Installing sample config files
  make:
   chdir: /downloads/nagios-4.2.1
   target: install-config

- name: Installing set permissions
  make:
   chdir: /downloads/nagios-4.2.1
   target: install-commandmode

- name: Installing Nagios web interface
  make:
   chdir: /downloads/nagios-4.2.1
   target: install-webconf

- name: Installing pip
  apt:
   name: python3-pip
   state: latest

- name: Installing htpasswd module
  pip: 
   name: passlib
   state: latest

- name: Creating nagiosadmin account
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users 
    name: nagiosadmin
    password: "12345"
    crypt_scheme: md5_crypt

- name: Restarting Apache
  service:
   name: apache2
   state: reloaded
