---
# tasks file for roles/influxdb
- name: Importing the Influxdb public GPG key into APT
  apt_key:
   url: https://repos.influxdata.com/influxdb.key
   state: present

- name: Adding Influxdb source list
  apt_repository:
    repo: deb https://repos.influxdata.com/ubuntu focal stable
    state: present

- name: Updating Packages
  apt:
   update_cache: yes

- name: Installing influxdb
  apt:
   name: influxdb
   update_cache: yes

- name: Starting influxdb
  service:
   name: influxdb
   state: started
   enabled: yes


- name: Activating Firewall
  ufw:
   state: enabled

- name: Opening the port
  ufw:
   rule: allow
   proto: tcp
   port: '8086'

