---
# tasks file for roles/elasticsearch
- name: Install Docker
  apt:
   name: 
   - docker.io
   - python3-pip
   state: latest
   update_cache: yes

- name: Install docker module
  pip: 
   name: docker
   state: latest

- name: Start docker
  service:
   name: docker
   state: started
   enabled: yes

- name: Download and create elasticsearch container
  docker_container:
   name: elasticsearch
   image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
   env:
    discovery.type: "single-node"
   ports:
      - 9200:9200
      - 9300:9300

- name: Test elasticsearch installation
  uri:
   url: "http://localhost:9200"
   method: GET
   return_content: yes
   validate_certs: no
  register: elastest

- name: Show the test result
  debug: var=elastest


