---
# tasks file for roles/mariadb
- name: Updating Packages
  apt:
   update_cache: yes

- name: Installing MariaDB
  apt:
   name: mariadb-server
   state: latest
   update_cache: yes

- name: Starting Mariadb
  service:
   name: mariadb
   state: started
   enabled: yes

